eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-sr:8761/eureka/

server:
  port: 9090

spring:
  application:
    name: Gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Projectinfo
          uri: http://project-sr:9091
          predicates:
            - Path=/project/**
          filters:
            - AuthenticationFilter
        - id: Employeeinfo
          uri: http://employee-sr:9092
          predicates:
            - Path=/ustemps/**
          filters:
            - AuthenticationFilter
        - id: authentication-service
          uri: http://authentication-sr:9095
          predicates:
            - Path=/api/auth/**
